/* CH32V307 */
/* see https://docs.rs/riscv-rt/latest/riscv_rt/index.html */
MEMORY
{
	FLASH : ORIGIN = 0x00000000, LENGTH = 256k
	RAM : ORIGIN = 0x20000000, LENGTH = 64k
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);

