[build]
target = "riscv32imac-unknown-none-elf"
rustflags = [
  #"-C", "link-arg=-Tdevice.x",
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
  #"-C", "link-arg=-nostartfiles",
  #"-C", "-Xlinker",
  #"-C", "--gc-sections",
  #"-C", "link-arg=-nostdlib",
]
